"""
Query Engine Module
Handles question answering using Ollama with document context
"""

import logging
import asyncio
import threading
import json
from pathlib import Path
from typing import Dict

logger = logging.getLogger(__name__)


class QueryEngine:
    """
    Handles query processing using direct Ollama approach
    Loads documents and generates answers based on context
    """
    
    def __init__(self, working_dir: str = "data/rag_workspace", model_name: str = "gemma3:12b"):
        """
        Initialize query engine
        
        Args:
            working_dir: Directory containing document storage
            model_name: Ollama model name to use for generation
        """
        self.working_dir = Path(working_dir)
        self.model_name = model_name
    
    def query(self, question: str, mode: str = "hybrid") -> str:
        """
        Process a query and return an answer
        
        Args:
            question: Question to ask about the documents
            mode: Query mode (kept for API compatibility, not currently used)
            
        Returns:
            Answer generated by Ollama based on document content
        """
        try:
            logger.info(f"Processing query with mode: {mode}")
            logger.info(f"Question: {question[:100]}...")
            
            # Run async query in a new thread with its own event loop
            # This avoids conflicts with Streamlit's event loop
            result = {'response': None, 'error': None}
            
            def run_in_thread():
                try:
                    loop = asyncio.new_event_loop()
                    asyncio.set_event_loop(loop)
                    result['response'] = loop.run_until_complete(self._query_async(question, mode))
                except Exception as e:
                    result['error'] = e
                finally:
                    # Clean up pending tasks before closing loop
                    try:
                        pending = asyncio.all_tasks(loop)
                        if pending:
                            for task in pending:
                                if not task.done():
                                    task.cancel()
                            loop.run_until_complete(asyncio.gather(*pending, return_exceptions=True))
                    except Exception:
                        pass
                    finally:
                        loop.close()
            
            thread = threading.Thread(target=run_in_thread, daemon=True)
            thread.start()
            thread.join(timeout=120)  # 2 minute timeout
            
            if result['error']:
                logger.error(f"Query error: {result['error']}")
                return f"⚠️ Query failed: {str(result['error'])[:200]}"
            
            response = result['response']
            if response:
                logger.info("Query processed successfully")
                return response
            else:
                logger.warning("Query returned None")
                return "⚠️ No response generated. The system may still be initializing."
            
        except Exception as e:
            logger.error(f"Failed to process question: {e}")
            return f"⚠️ Query failed: {str(e)[:200]}"
    
    async def _query_async(self, question: str, mode: str) -> str:
        """
        Async helper for querying using direct Ollama approach
        
        Args:
            question: Question to ask
            mode: Query mode (not currently used)
            
        Returns:
            Generated answer
        """
        try:
            # Direct approach: Load documents and use Ollama to generate answers
            import ollama
            
            # Get document content directly from storage
            kv_store_path = self.working_dir / "kv_store_full_docs.json"
            
            if not kv_store_path.exists():
                return "⚠️ No documents found. Please ingest documents first."
            
            # Load documents
            with open(kv_store_path, 'r') as f:
                docs = json.load(f)
            
            if not docs:
                return "⚠️ No documents available. Please ingest documents first."
            
            # Get all document content
            context_parts = []
            for doc_id, doc_data in docs.items():
                content = doc_data.get('content', '')
                filename = doc_data.get('file_path', 'unknown')
                context_parts.append(f"From {filename}:\n{content}")
            
            context = "\n\n---\n\n".join(context_parts)
            
            # Create prompt for Ollama
            prompt = f"""Based on the following document content, please answer the question accurately and concisely.

DOCUMENT CONTENT:
{context}

QUESTION: {question}

ANSWER (provide a clear, direct answer based only on the information in the documents):"""
            
            # Call Ollama directly
            logger.info(f"Calling Ollama with question: {question[:100]}...")
            
            response = ollama.chat(
                model=self.model_name,
                messages=[
                    {
                        'role': 'system',
                        'content': 'You are a helpful assistant that answers questions based on provided documents. Be accurate and cite specific information from the documents.'
                    },
                    {
                        'role': 'user',
                        'content': prompt
                    }
                ],
                options={
                    'temperature': 0.7,
                    'num_predict': 2000
                }
            )
            
            answer = response['message']['content']
            logger.info("Successfully generated answer using Ollama")
            return answer
            
        except Exception as e:
            error_msg = str(e)
            logger.error(f"Query error: {error_msg}")
            return f"⚠️ Query failed: {error_msg[:200]}"

